---
title: "Misc Data"
author: "jemus42"
output:
  html_document:
    fig_width: 9
    theme: spacelab
    toc: yes
---

```{r startup, echo=FALSE,message=FALSE}
library("dplyr")
library("wurstmineR")
library("networkD3")

people <- wurstmineR::getActivePeople(size = "full")

ppl    <- people[c("invitedBy", "id", "color", "joinStatus", "name")] %>%
            arrange(invitedBy) %>%
            filter(!is.na(invitedBy))
```

## People as a Network of Invitations

```{r d3,echo=F}
simpleNetwork(ppl[c("id", "invitedBy")], fontSize = 14, textColour = "black", linkDistance = 200, charge = -200)
```

## Invite Tree

```{r mermaid,echo=F}
paste0(ppl$invitedBy, "-->", ppl$id, collapse = ";") %>%
           paste("graph TD", ., sep = ";") %>%
           mermaid
```

## Time Series of Session Data

```{r timeSeries, echo=FALSE,message=FALSE}
library("tidyr")
library("xts")
library("dygraphs")

ptime <- spread(playedPerPerson[c("person", "timePlayed", "date")], key = "person", value = "timePlayed") %>%
           select(-date) %>%
           xts(order.by = unique(playedPerPerson$date))
ptime[is.na(ptime)] <- 0


p <- dygraph(ptime) %>% 
      dyOptions(stackedGraph = TRUE, fillGraph = TRUE, fillAlpha = 0.4) %>%
      dyRangeSelector(dateWindow = c(as.character(Sys.Date()-100), as.character(Sys.Date()))) %>%
      dyRoller(rollPeriod = 1) %>%
      dyEvent(date = "2013-12-19", "Great Outage of 2013", labelLoc = "top") %>%
      dyShading(from = "2013-12-19", to = "2014-01-02") %>%
      dyLegend(width = 600, show = "onmouseover", showZeroValues = F) %>%
      dyAxis("y", label = "Time Active (min)") %>%
      dyHighlight(highlightCircleSize = 5,
                  hideOnMouseOut = TRUE)
p
```

## Session Data as a Table (SDaaT)

### Total Time Played per Person

```{r tables, echo = FALSE, message = FALSE}
library("DT")

datatable(playtime.people, options = list(pageLength = -1))
```

### Time Played per Year per Person

```{r perYear, echo = FALSE, message = FALSE}
datatable(playedPerYear, options = list(pageLength = 20))

```

## Money Stuffs

```{r moneys, echo = FALSE, message = FALSE}
#### Data cleanup ####
library("ggplot2")
library("lubridate")
library("scales")
library("dplyr")

moneys       <- httr::GET("http://wurstmineberg.de/assets/serverstatus/moneys.json") %>%
                  httr::content(as = "text") %>% jsonlite::fromJSON(.)
moneys       <- moneys$history
moneys$date  <- as.POSIXct(moneys$date)
moneys$total <- numeric(length(moneys$amount))

for (i in 1:(length(moneys$amount))){
  if (i == 1){
    moneys$total[i] <- moneys$amount[1]
  } else {
    moneys$total[i] <- moneys$total[i-1] + moneys$amount[i]
  }
}

moneys$transaction[moneys$type %in% c("monthly", "unique")]       <- "Expense"
moneys$transaction[moneys$type %in% c("player", "playerMonthly")] <- "Income"

#### Information ####
moneys %>% group_by(type) %>% summarize(sum = sum(amount)) %>% knitr::kable()

#### Plots ####
moneys_totals <- moneys %>% group_by(type) %>% summarize(amount = sum(amount))
moneys_totals$transaction[moneys_totals$type %in% c("monthly", "unique")]       <- "Expense"
moneys_totals$transaction[moneys_totals$type %in% c("player", "playerMonthly")] <- "Income"

ggplot(data = moneys_totals, aes(x = transaction, y = abs(amount), fill = type)) +
  geom_bar(stat = "identity", position = "stack", colour = "black") +
  labs(title = "Transactions", y = "Amount (€)", x = "Transaction Type")

#### Transaction history ####
moneydays <- seq.Date(from = as.Date(moneys$date[1]), to = last(as.Date(moneys$date)), by = "days")
totals    <- plyr::rbind.fill(moneys, data.frame(date = moneydays)) %>% arrange(date)
totals    <- totals[-1, ]

for (i in 1:nrow(totals)){
  if (is.na(totals$total[i])){
    totals$total[i] <- totals$total[i-1]
  }
}

totals$date <- as.POSIXct(totals$date)
totals$year <- year(totals$date)

ggplot(data = totals, aes(x = date, y = total)) +
  geom_line(size = 1, alpha = .4) +
  geom_point(size = 2) +
  geom_smooth(method = loess, colour = "blue", se = F) +
  geom_hline(y = 0, size = 1, colour = "red") +
  geom_hline(y = mean(totals$total), linetype = "dotdash") +
  geom_hline(y = 59, colour = "green") +
  scale_x_datetime(labels = date_format("%Y-%B"),
                   breaks = date_breaks("months"),
                   minor_breaks = "weeks") +
  scale_y_continuous(breaks = pretty_breaks(), minor_breaks = seq(-200, 200, 10)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Wurstmineberg Funding History", x = "Date", y = "Total (€)")


moneys %>% select(total) %>% xts::xts(order.by = moneys$date) %>%
  dygraph(main = "Wurstmineberg Funding", ylab = "Account Status (€)") %>%
  dyOptions(fillGraph = TRUE, fillAlpha = 0.7, stepPlot = T, drawPoints = TRUE, pointSize = 2) %>%
  dyRangeSelector(dateWindow = c(as.POSIXct("2015-01-01"), max(moneys$date)))
```

