---
title: "Entity Stats"
author: '[jemus42](https://github.com/jemus42)'
date: "Rendered at `r format(Sys.time(), '%F %H:%M:%S')`"
output: 
  html_document:
    fig_width: 9
    self_contained: no
    toc: yes
    toc_depth: 1
---

```{r init, echo=F, message=F}
suppressPackageStartupMessages(library(wurstmineR))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))

load("cache/workspace.RData")
source("functions.R")
```

# Kills and Deaths by Entities

```{r plot_gen, cache=FALSE, results='asis', echo=FALSE}
mobStats <- dplyr::arrange_(mobStats, "mob", "action")

for(i in seq_along(mobStats$stat)){
  
  stat       <- mobStats$stat[i]
  action     <- mobStats$action[i]
  mobName    <- mobStats$mob[i]
  filename   <- paste0("output/entities/", stat, ".png")
  
  if (action == "killed"){
    title    <- paste0("Times mob “", mobName, "” was killed")
    ylab     <- "Kills"
  } else if (action == "killed by"){
    title    <- paste0("Deaths caused by mob “", mobName, "”")
    ylab     <- "Caused Deaths"
  }
  
  p <- ggplot(data  = stats$entities)
  p <- p + aes(x    = sortLevels(person, stats$entities[[stat]]), 
               y    = stats$entities[[stat]])
  p <- p + barChart + coord_flip() + scale_y_discrete(breaks = scales::pretty_breaks())
  p <- p + labs(x = "Person", y = ylab, title = title)
  
  ggsave(plot = p, file = filename, height = plotHeight, width = plotWidth)
  
  # Output
  verbatim_title_md(stat, stat, i, title, stat)
  verbatim_image_md(title, "/wurstminestats/entities/", stat)
}

```

# Summary Statistics for Entity Related Deaths and Kills

```{r summary, cache=FALSE, results='asis', echo=FALSE}
# Kills per mob #
mobsKilled <- mobStats[mobStats$action == "killed", ]

p <- ggplot(data = mobsKilled)
p <- p + aes(x = sortLevels(mob, total), y = total)
p <- p + barChart + coord_flip() + scale_y_discrete(breaks = scales::pretty_breaks())
p <- p + labs(x = "Mobs", y = "Kills", title = "Killed Mobs")
ggsave(plot = p, file = "output/entities/Kills_byMob.png", height = plotHeight, width = plotWidth)

verbatim_title_md("Kills_byMob", number = 1, title = "Killed Mobs")
verbatim_image_md("Kills_byMob", base_path = "/wurstminestats/entities/", filename = "Kills_byMob")

# … Let's filter out Endermen #
mobsKilledFiltered <- mobsKilled[mobsKilled$mob != "Enderman", ]

p <- ggplot(data = mobsKilledFiltered) 
p <- p + aes(x = reorder(mob, total), y = total)
p <- p + barChart + coord_flip() + scale_y_discrete(breaks = scales::pretty_breaks())
p <- p + labs(x = "Mobs", y = "Kills", title = "Killed Mobs (except Endermen)")
ggsave(plot=p, file="output/entities/Kills_byMob_except_Endermen.png", height=plotHeight, width=plotWidth)

verbatim_title_md("Kills_byMob_except_Endermen", number = 2, title = "Killed Mobs (except Endermen)")
verbatim_image_md("Kills_byMob_except_Endermen", base_path = "/wurstminestats/entities/", filename = "Kills_byMob_except_Endermen")

#### Deaths by mob ####
mobsKilledBy <- mobStats[mobStats$action == "killed by", ]

p <- ggplot(data = mobsKilledBy) 
p <- p + aes(x = sortLevels(mob, total), y = total)
p <- p + barChart + coord_flip() + scale_y_discrete(breaks = scales::pretty_breaks())
p <- p + labs(x = "Mobs", y = "Deaths", title = "Deaths by Mob")
ggsave(plot = p, file = "output/entities/Deaths_byMob.png", height = plotHeight, width = plotWidth)

verbatim_title_md("Deaths_byMob", number = 3, title = "Deaths by Mob")
verbatim_image_md("Deaths_byMob", base_path = "/wurstminestats/entities/", filename = "Deaths_byMob")

### 

statsByKey        <- stats$entities %>% gather("stat", "value", -person)
statsByKey$action <- 0
statsByKey$action[grep("killEntity",      statsByKey$stat)] <- "killed"
statsByKey$action[grep("entityKilledBy.", statsByKey$stat)] <- "killed by"
statsByKey$mob <- as.factor(extractMobNames(statsByKey$stat))

## Mob Kills

p <- ggplot(data = filter(statsByKey, action == "killed")) 
p <- p + aes(x = sortLevels(person, value), y = value, fill = mob)
p <- p + barChart + coord_flip() + scale_y_discrete(breaks = scales::pretty_breaks())
p <- p + labs(x = "Person", y = "Kills", title = "Mob Kills", fill = "Mob") +
  theme(legend.key.size = unit(0.4, "cm"))
ggsave(plot = p, file = "output/entities/mobKills_perPerson.png", height = plotHeight, width = plotWidth * 1.5)

verbatim_title_md("mobKills_perPerson", number = 4, title = "Mob Kills")
verbatim_image_md("mobKills_perPerson", base_path = "/wurstminestats/entities/", filename = "mobKills_perPerson")

## Mob Kills without Endermen

p <- ggplot(data = filter(statsByKey, action == "killed", mob != "Enderman")) 
p <- p + aes(x = sortLevels(person, value), y = value, fill = mob)
p <- p + barChart + coord_flip() + scale_y_discrete(breaks = scales::pretty_breaks())
p <- p + labs(x = "Person", y = "Kills", title = "Mob Kills (except Endermen)", fill = "Mob") +
  theme(legend.key.size = unit(0.4, "cm"))
ggsave(plot = p, file = "output/entities/mobKills_perPerson_noendermen.png", height = plotHeight, width = plotWidth * 1.5)

verbatim_title_md("mobKills_perPerson_noendermen", number = 4, title = "Mob Kills (except Endermen)")
verbatim_image_md("mobKills_perPerson_noendermen", base_path = "/wurstminestats/entities/", filename = "mobKills_perPerson_noendermen")


## Deaths by Mob
p <- ggplot(data = filter(statsByKey, action == "killed by")) 
p <- p + aes(x = sortLevels(person, value), y = value, fill = mob)
p <- p + barChart + coord_flip() + scale_y_discrete(breaks = scales::pretty_breaks())
p <- p + labs(x = "Person", y = "Times Killed by Mob", title = "Mob Kills", fill = "Mob") +
  theme(legend.key.size = unit(0.6, "cm"))

ggsave(plot = p, file = "output/entities/mobDeaths_perPerson.png", height = plotHeight, width = plotWidth * 1.5)

verbatim_title_md("mobDeaths_perPerson", number = 4, title = "Times Killed by Mob")
verbatim_image_md("mobDeaths_perPerson", base_path = "/wurstminestats/entities/", filename = "mobDeaths_perPerson")
```

